-- Add potentially missing columns to papers table
ALTER TABLE papers ADD COLUMN IF NOT EXISTS citation_count INTEGER DEFAULT 0;
ALTER TABLE papers ADD COLUMN IF NOT EXISTS source VARCHAR(255);
ALTER TABLE papers ADD COLUMN IF NOT EXISTS venue VARCHAR(255);
ALTER TABLE papers ADD COLUMN IF NOT EXISTS doi VARCHAR(255);
ALTER TABLE papers ADD COLUMN IF NOT EXISTS pdf_url VARCHAR(500);
ALTER TABLE papers ADD COLUMN IF NOT EXISTS publication_date TIMESTAMP;
ALTER TABLE papers ADD COLUMN IF NOT EXISTS authors JSON;
ALTER TABLE papers ADD COLUMN IF NOT EXISTS abstract TEXT;
ALTER TABLE papers ADD COLUMN IF NOT EXISTS title VARCHAR(500);
